//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EFTN.NrbIBReturn {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback returnMappFcdbEftnWebServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::EFTN.Properties.Settings.Default.EFTN_NrbIBReturn_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event returnMappFcdbEftnWebServiceCompletedEventHandler returnMappFcdbEftnWebServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/returnMappFcdbEftnWebService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int returnMappFcdbEftnWebService(string ACTIONUSER_ID, string IDFCATREF, string STATUS, string RETURN_REASON, string RETURN_CODE, string RETURN_FCCREFF, string REMARKS, string REMARKS1) {
            object[] results = this.Invoke("returnMappFcdbEftnWebService", new object[] {
                        ACTIONUSER_ID,
                        IDFCATREF,
                        STATUS,
                        RETURN_REASON,
                        RETURN_CODE,
                        RETURN_FCCREFF,
                        REMARKS,
                        REMARKS1});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void returnMappFcdbEftnWebServiceAsync(string ACTIONUSER_ID, string IDFCATREF, string STATUS, string RETURN_REASON, string RETURN_CODE, string RETURN_FCCREFF, string REMARKS, string REMARKS1) {
            this.returnMappFcdbEftnWebServiceAsync(ACTIONUSER_ID, IDFCATREF, STATUS, RETURN_REASON, RETURN_CODE, RETURN_FCCREFF, REMARKS, REMARKS1, null);
        }
        
        /// <remarks/>
        public void returnMappFcdbEftnWebServiceAsync(string ACTIONUSER_ID, string IDFCATREF, string STATUS, string RETURN_REASON, string RETURN_CODE, string RETURN_FCCREFF, string REMARKS, string REMARKS1, object userState) {
            if ((this.returnMappFcdbEftnWebServiceOperationCompleted == null)) {
                this.returnMappFcdbEftnWebServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreturnMappFcdbEftnWebServiceOperationCompleted);
            }
            this.InvokeAsync("returnMappFcdbEftnWebService", new object[] {
                        ACTIONUSER_ID,
                        IDFCATREF,
                        STATUS,
                        RETURN_REASON,
                        RETURN_CODE,
                        RETURN_FCCREFF,
                        REMARKS,
                        REMARKS1}, this.returnMappFcdbEftnWebServiceOperationCompleted, userState);
        }
        
        private void OnreturnMappFcdbEftnWebServiceOperationCompleted(object arg) {
            if ((this.returnMappFcdbEftnWebServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.returnMappFcdbEftnWebServiceCompleted(this, new returnMappFcdbEftnWebServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void returnMappFcdbEftnWebServiceCompletedEventHandler(object sender, returnMappFcdbEftnWebServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class returnMappFcdbEftnWebServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal returnMappFcdbEftnWebServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591