//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTN {
    
    public partial class CorToCor {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form2;
        protected EFTN.modules.MakerHeader Header1;
        protected System.Web.UI.WebControls.TextBox txtCompanyTIN;
        protected System.Web.UI.WebControls.RequiredFieldValidator ReqtxtCompanyTIN;
        protected System.Web.UI.WebControls.DropDownList ddListTypeOfPayment;
        protected System.Web.UI.WebControls.TextBox txtCompanyName;
        protected System.Web.UI.WebControls.RequiredFieldValidator ReqtxtCompanyName;
        protected System.Web.UI.WebControls.Button btnCorToCorNext;
        protected System.Web.UI.UserControl Footer1;
    }
}
