//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTN {
    
    public partial class EFTCheckerEBBS {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected EFTN.modules.CheckerHeader Header1;
        protected System.Web.UI.WebControls.Label lblCountOutwardTransSent;
        protected System.Web.UI.WebControls.Label lblCountInwardTransactionSent;
        protected System.Web.UI.WebControls.Label lblCountBatchSent;
        protected System.Web.UI.WebControls.Label lblCountOutwardReturnSent;
        protected System.Web.UI.WebControls.Label lblCountOutwardNOCSent;
        protected System.Web.UI.WebControls.Label lblCountDishonorSent;
        protected System.Web.UI.WebControls.Label lblCountInwardReturn;
        protected System.Web.UI.UserControl Footer1;
    }
}
