//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTN {
    
    public partial class EFTDataTransferToPIBS {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected EFTN.modules.CheckerHeader Header1;
        protected System.Web.UI.WebControls.LinkButton linkBtnInsertInwardTransaction;
        protected System.Web.UI.WebControls.LinkButton linkBtnSendOutwardReturnFromPIBStoFlora;
        protected System.Web.UI.WebControls.LinkButton linkBtnSendApprovedInwardTxnFromPIBStoFlora;
        protected System.Web.UI.WebControls.Label Msg;
        protected System.Web.UI.UserControl Footer1;
    }
}
