//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTN {
    
    public partial class EFTEditNOC {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected EFTN.modules.MakerHeader Header1;
        protected System.Web.UI.WebControls.Repeater rptEditNOC;
        protected System.Web.UI.WebControls.RadioButtonList rblTransactionDecision;
        protected System.Web.UI.WebControls.DropDownList ddlReturnChangeCode;
        protected System.Web.UI.WebControls.Label lblCorrectedDataMsg;
        protected System.Web.UI.WebControls.TextBox txtCorrectedData;
        protected System.Web.UI.WebControls.LinkButton btnSave;
        protected System.Web.UI.UserControl Footer1;
    }
}
