//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTN {
    
    public partial class FlatFileUpdloadForTransactionSent {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected EFTN.modules.CheckerHeader Header1;
        protected System.Web.UI.WebControls.FileUpload fulExcelFile;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfvFulExcelFile;
        protected System.Web.UI.WebControls.Button btnUploadExcel;
        protected System.Web.UI.WebControls.Label lblErrMsg;
        protected System.Web.UI.UserControl Footer1;
    }
}
