//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTN {
    
    public partial class ImportRNOC {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected EFTN.modules.Header Header1;
        protected System.Web.UI.WebControls.DataGrid dtgListOfRNOCXML;
        protected System.Web.UI.WebControls.CheckBox cbxSelectAll;
        protected System.Web.UI.WebControls.LinkButton btnImportRNOC;
        protected System.Web.UI.WebControls.Label lblImportedData;
        protected System.Web.UI.WebControls.DataGrid dtgInwardRNOC;
        protected System.Web.UI.UserControl Footer1;
    }
}
