//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTN {
    
    public partial class MismatchedInwardReturn {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected EFTN.modules.MakerHeader Header1;
        protected System.Web.UI.WebControls.DataGrid dtgInwardReturnMaker;
        protected System.Web.UI.UserControl Footer1;
    }
}
