//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloraSoft {
    
    public partial class ResetPassword {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected EFTN.modules.Header Header;
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.WebControls.TextBox txtNewPassword;
        protected System.Web.UI.WebControls.Label Label3;
        protected System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected System.Web.UI.WebControls.CompareValidator CompareValidatorPassword;
        protected System.Web.UI.WebControls.Button btnSubmit;
        protected System.Web.UI.WebControls.Button btnCancel;
        protected System.Web.UI.WebControls.Label Msg;
        protected System.Web.UI.WebControls.Label lblTestCookie;
        protected System.Web.UI.UserControl Footer1;
    }
}
