//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTN {
    
    public partial class RNOCofReceivedNOCRejectedByChecker {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected EFTN.modules.MakerHeader Header1;
        protected System.Web.UI.WebControls.DataGrid dtgEFTRNOCOfReceivedNOCRejectedList;
        protected System.Web.UI.WebControls.Label lblRNOCMsg;
        protected System.Web.UI.WebControls.Label lblRefusedCORCode;
        protected System.Web.UI.WebControls.DropDownList ddlRefusedCORCode;
        protected System.Web.UI.WebControls.Label lblCorrectedDataMsg;
        protected System.Web.UI.WebControls.TextBox txtCorrectedData;
        protected System.Web.UI.WebControls.LinkButton btnSave;
        protected System.Web.UI.WebControls.LinkButton lnkBtnNOC;
        protected System.Web.UI.UserControl Footer1;
    }
}
