//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTN {
    
    public partial class TransactionManager {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected EFTN.modules.AdminChecker Header1;
        protected System.Web.UI.WebControls.Label lblDay;
        protected System.Web.UI.WebControls.Label lblDate;
        protected System.Web.UI.WebControls.DropDownList ddlistDay;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.DropDownList ddlistMonth;
        protected System.Web.UI.WebControls.Label Label46;
        protected System.Web.UI.WebControls.DropDownList ddlistYear;
        protected System.Web.UI.WebControls.DropDownList ddListTransactionType;
        protected System.Web.UI.WebControls.Button btnDelete;
        protected System.Web.UI.WebControls.Label lblMsg;
        protected System.Web.UI.UserControl Footer1;
    }
}
