//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloraSoft {
    
    public partial class UpdateInactiveBranch6786 {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected EFTN.modules.AdminChecker Header;
        protected System.Web.UI.WebControls.CheckBox cbxAll;
        protected System.Web.UI.WebControls.Button btnActive;
        protected System.Web.UI.WebControls.Button btnInactive;
        protected System.Web.UI.WebControls.DataGrid MyDataGrid;
        protected System.Web.UI.UserControl Footer1;
    }
}
