//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTN {
    
    public partial class UpdateHolidayCalendarMaker {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected EFTN.modules.MakerHeader Header1;
        protected System.Web.UI.WebControls.Label lblHolidayCalendar;
        protected System.Web.UI.WebControls.Calendar calendarHoliday;
        protected System.Web.UI.WebControls.Label lblDesc;
        protected System.Web.UI.WebControls.TextBox txtHolidayDesc;
        protected System.Web.UI.WebControls.Button btnUpdate;
        protected System.Web.UI.WebControls.Button btnCancel;
        protected System.Web.UI.WebControls.Panel pnlHolidays;
        protected System.Web.UI.WebControls.DataGrid dtgHolidays;
        protected System.Web.UI.UserControl Footer1;
    }
}
